### ISSUE TITLE
role is broken for CentOS6 (at least)

### ISSUE THREAD

**Issue by kostyrev** [picotrading/ansible-sudo#3]
how to reproduce

```
ansible-galaxy install jtyr.sudo -p roles
```

attach to host

```
- hosts: sandbox
  roles:
    - jtyr.sudo
```

ansible run gives

```
TASK: [jtyr.sudo | Create /etc/sudoers file] ********************************** 
failed: [sandbox.kostyrev.avp.ru] => {"failed": true}
msg: failed to validate: rc:1 error:visudo: >>> /root/.ansible/tmp/ansible-tmp-1439113549.1-246969111316984/source: syntax error near line 23 <<<

```

я худею, люди выкладывают нерабочие модули прямо в галакси.

**Comment by ypid** [comment]
Please provide the output of `type -a visudo`.

I think we should remove the `sudo_visudo` variable and relay on `$PATH` to be set correctly and not be malicious.

**Comment by kostyrev** [comment]
]# type -a visudo
visudo is /usr/sbin/visudo

But I don't follow how it is relevant.

**Comment by ypid** [comment]
Thats is then not the problem. Try running `ansible-playbook --check --diff $playbook`.

**Comment by kostyrev** [comment]
wat??
I've already resolved that issue and referenced it.

**Comment by ypid** [comment]
Sorry, I missed the reference.
